version: 2

defaults: &defaults
  docker:
    - image: circleci/node:erbium
  working_directory: ~/repo

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test:junit

      - store_test_results:
          path: test-results

      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run: echo "access=public" >> ~/repo/.npmrc
      - run:
          name: Publish package
          command: yarn release

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:
            branches:
              only:
                - /.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
