name: Validate

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.6

      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          # This makes Actions fetch all Git history so that chromatic can diff against previous commits
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Test
        run: pnpm test

      - name: Test Reports
        run: pnpm test:junit

      - name: Echo
        run: ls

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "**/test-results/*.xml"
